### PR TITLE
Resolves #41, Remove ancillary chunks in the generated PNG file

### LINKED ISSUE #41: Tests should not use the size of the file since this information is unreliable
Currently the tests fail intermittently depending on the environment. We should not use the size of the file in the tests suite.

Maybe a md5sum of the file will be more reliable ?

### PR DESCRIPTION
**Pull request by Mogztter**
I believe the tests are randomly failing because the PNG file contains "unstable" metadata.
This pull request remove all ancillary chunks to keep only critical chunks: https://en.wikipedia.org/wiki/Portable_Network_Graphics#File_format

With this change, the md5sum should be stable.

### CODE REVIEW

File: test/png-metadata.js [hunk 1]
```diff
@@ -0,0 +1,87 @@
+// Adapted from https://github.com/kujirahand/node-png-metadata/blob/master/src/lib/png-metadata.js
+// Fix an iteration issue in the 'joinChunk' function
```
Comment (Mogztter) [inline test/png-metadata.js]: I'm not using the package https://www.npmjs.com/package/png-metadata because the `joinChunk` contains a bug

**Comment by Mogztter** [comment]
@eshepelyuk Confirmed the chunk `iTxt` contains the following:

```
@startuml
alice -> bob
bob ..> alice
@enduml

PlantUML version 1.2018.15beta2(Unknown compile time)
(GPL source distribution)
Java Runtime: Java(TM) SE Runtime Environment
JVM: Java HotSpot(TM) 64-Bit Server VM
Java Version: 1.7.0_25-b15
Operating System: Linux
Default Encoding: UTF-8
Language: en
Country: US

```

The source of the diagram is stable but the PlantUML version will likely change.
For reference I've used https://github.com/finnp/png-itxt to read the `iTXt` chunk.

**Comment by Mogztter** [comment]
SVG files are also "unstable":

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" contentScriptType="application/ecmascript" contentStyleType="text/css" height="112px" preserveAspectRatio="none" style="width:119px;height:112px;" version="1.1" viewBox="0 0 119 112" width="119px" zoomAndPan="magnify"><defs><filter height="300%" id="f1keim8oeuimdl" width="300%" x="-1" y="-1"><feGaussianBlur result="blurOut" stdDeviation="2.0"/><feColorMatrix in="blurOut" result="blurOut2" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 .4 0"/><feOffset dx="4.0" dy="4.0" in="blurOut2" result="blurOut3"/><feBlend in="SourceGraphic" in2="blurOut3" mode="normal"/></filter></defs>
<g><line style="stroke: #A80036; stroke-width: 1.0; stroke-dasharray: 5.0,5.0;" x1="32" x2="32" y1="38.2969" y2="72.2969"/><line style="stroke: #A80036; stroke-width: 1.0; stroke-dasharray: 5.0,5.0;" x1="89" x2="89" y1="38.2969" y2="72.2969"/><rect fill="#FEFECE" filter="url(#f1keim8oeuimdl)" height="30.2969" style="stroke: #A80036; stroke-width: 1.5;" width="45" x="8" y="3"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacingAndGlyphs" textLength="31" x="15" y="22.9951">alice</text><rect fill="#FEFECE" filter="url(#f1keim8oeuimdl)" height="30.2969" style="stroke: #A80036; stroke-width: 1.5;" width="45" x="8" y="71.2969"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacingAndGlyphs" textLength="31" x="15" y="91.292">alice</text><rect fill="#FEFECE" filter="url(#f1keim8oeuimdl)" height="30.2969" style="stroke: #A80036; stroke-width: 1.5;" width="41" x="67" y="3"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacingAndGlyphs" textLength="27" x="74" y="22.9951">bob</text><rect fill="#FEFECE" filter="url(#f1keim8oeuimdl)" height="30.2969" style="stroke: #A80036; stroke-width: 1.5;" width="41" x="67" y="71.2969"/><text fill="#000000" font-family="sans-serif" font-size="14" lengthAdjust="spacingAndGlyphs" textLength="27" x="74" y="91.292">bob</text><polygon fill="#A80036" points="77.5,50.2969,87.5,54.2969,77.5,58.2969,81.5,54.2969" style="stroke: #A80036; stroke-width: 1.0;"/><line style="stroke: #A80036; stroke-width: 1.0;" x1="32.5" x2="83.5" y1="54.2969" y2="54.2969"/>
<!--
@startuml
alice -> bob
@enduml

PlantUML version 1.2018.15beta2(Unknown compile time)
(GPL source distribution)
Java Runtime: Java(TM) SE Runtime Environment
JVM: Java HotSpot(TM) 64-Bit Server VM
Java Version: 1.7.0_25-b15
Operating System: Linux
Default Encoding: UTF-8
Language: en
Country: US
-->
</g>
</svg>
```

```xml
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.38.0 (20140413.2041) -->
<!-- Title: foo Pages: 1 -->
<svg width="100pt" height="222pt"
 viewBox="0.00 0.00 99.92 222.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 218)">
<title>foo</title>
<polygon fill="white" stroke="none" points="-4,4 -4,-218 95.9157,-218 95.9157,4 -4,4"/>
<!-- node1 -->
<g id="node1" class="node"><title>node1</title>
<path fill="none" stroke="black" d="M60.9579,-214C60.9579,-214 30.9579,-214 30.9579,-214 24.9579,-214 18.9579,-208 18.9579,-202 18.9579,-202 18.9579,-190 18.9579,-190 18.9579,-184 24.9579,-178 30.9579,-178 30.9579,-178 60.9579,-178 60.9579,-178 66.9579,-178 72.9579,-184 72.9579,-190 72.9579,-190 72.9579,-202 72.9579,-202 72.9579,-208 66.9579,-214 60.9579,-214"/>
<text text-anchor="middle" x="45.9579" y="-192.3" font-family="Times,serif" font-size="14.00">node1</text>
</g>
<!-- node2 -->
<g id="node2" class="node"><title>node2</title>
<path fill="yellow" stroke="black" d="M34.7857,-137.62C34.7857,-137.62 11.2143,-128.38 11.2143,-128.38 5.62819,-126.19 5.62819,-121.81 11.2143,-119.62 11.2143,-119.62 34.7857,-110.38 34.7857,-110.38 40.3718,-108.19 51.544,-108.19 57.1301,-110.38 57.1301,-110.38 80.7014,-119.62 80.7014,-119.62 86.2875,-121.81 86.2875,-126.19 80.7014,-128.38 80.7014,-128.38 57.1301,-137.62 57.1301,-137.62 51.544,-139.81 40.3718,-139.81 34.7857,-137.62"/>
<text text-anchor="middle" x="45.9579" y="-120.3" font-family="Times,serif" font-size="14.00">node2</text>
</g>
<!-- node1&#45;&gt;node2 -->
<g id="edge1" class="edge"><title>node1&#45;&gt;node2</title>
<path fill="none" stroke="black" d="M45.9579,-177.697C45.9579,-169.983 45.9579,-160.712 45.9579,-152.112"/>
<polygon fill="black" stroke="black" points="49.458,-152.104 45.9579,-142.104 42.458,-152.104 49.458,-152.104"/>
</g>
<!-- node3 -->
<g id="node3" class="node"><title>node3</title>
<path fill="none" stroke="black" d="M30.9579,-0.5C30.9579,-0.5 60.9579,-0.5 60.9579,-0.5 66.9579,-0.5 72.9579,-6.5 72.9579,-12.5 72.9579,-12.5 72.9579,-57.5 72.9579,-57.5 72.9579,-63.5 66.9579,-69.5 60.9579,-69.5 60.9579,-69.5 30.9579,-69.5 30.9579,-69.5 24.9579,-69.5 18.9579,-63.5 18.9579,-57.5 18.9579,-57.5 18.9579,-12.5 18.9579,-12.5 18.9579,-6.5 24.9579,-0.5 30.9579,-0.5"/>
<text text-anchor="middle" x="45.9579" y="-54.3" font-family="Times,serif" font-size="14.00">a</text>
<polyline fill="none" stroke="black" points="18.9579,-46.5 72.9579,-46.5 "/>
<text text-anchor="middle" x="45.9579" y="-31.3" font-family="Times,serif" font-size="14.00">b</text>
<polyline fill="none" stroke="black" points="18.9579,-23.5 72.9579,-23.5 "/>
<text text-anchor="middle" x="45.9579" y="-8.3" font-family="Times,serif" font-size="14.00">c</text>
</g>
<!-- node2&#45;&gt;node3 -->
<g id="edge2" class="edge"><title>node2&#45;&gt;node3</title>
<path fill="none" stroke="black" d="M45.9579,-105.812C45.9579,-98.3278 45.9579,-89.1798 45.9579,-80.0019"/>
<polygon fill="black" stroke="black" points="49.458,-79.7143 45.9579,-69.7143 42.458,-79.7143 49.458,-79.7143"/>
</g>
</g>
</svg>
```

We should remove comments from the content because the Graphviz or the PlantUML versions can change.
